#!/bin/bash
if [ -e 8Mi-MCUpdCore.sh ]; then
    source 8Mi-MCUpdCore.sh || exit 1
else
    wget -O "8Mi-MCUpdCore.sh" https://github.com/8Mi-Tech/Shell/raw/main/8Mi-MCUpdCore.sh
    source 8Mi-MCUpdCore.sh || exit 1
fi

banner_install(){
    rm -rf ./_tmp-ci
    mkdir ./_tmp-ci/
    game_version=${minecraft_game_version:-"1.20"}
    fabric_loader_version=`curl -# https://meta.fabricmc.net/v2/versions/loader/$game_version | jq -r .[0].loader.version`
    fabric_installer_version=`curl -# https://meta.fabricmc.net/v2/versions/installer | jq -r .[0].version`
    curl -# -o "fabric-loader.jar" https://meta.fabricmc.net/v2/versions/loader/$game_version/$fabric_loader_version/$fabric_installer_version/server/jar
    modrinth_getLatestDownloadURL "fabric-api" "$game_version" | 8Mi_Download "FabricAPI.jar"
    jenkins_getLatestDownloadURL "https://ci.codemc.io/job/MohistMC/job/Banner-$game_version" | 8Mi_Download "BannerCore.jar"
    if [ ! -d "mods" ]; then
        mkdir "mods"
    fi
    cp ./_tmp-ci/*.jar ./mods/
    rm -rf ./_tmp-ci
}

banner_start(){
    if [ ${1:-false} = true ]; then
        banner_restart=true
    else
        banner_restart=false
    fi
    echo "eula=true" > eula.txt
    while true; do
        java $banner_java_options -jar fabric-loader.jar ${banner_options:-"-nogui"}
        if [ $banner_restart = false ]; then
            exit
        fi
    done
}


banner_launcher_update(){
    wget -O"${1}" https://github.com/8Mi-Tech/Shell/raw/main/banner-launcher
    exit
}

print_usage() {
    echo -e "    Usage: ${0} \n" \
            '   -i, --install       : Install Banner Server \n' \
            '   -j, --java-options  : Set Java options (Ex: -j "-Xmx2G" ) \n' \
            '   -o, --options       : Set Banner Option (Ex: -o "-nogui") (Default: "-nogui") \n' \
            '   -s, --start         : Start Banner Server \n' \
            '   -h, --help          : Print this help'
}
#start
main(){
    echo "[Banner Launcher] MohistMC Team"
    if [ ${1:-false} = false ]; then
        print_usage
        exit 0
    fi
    while true; do
        case "${1}" in
            -h | --help ) print_usage; exit 0 ;;
            -g | --game-version ) minecraft_game_version="${2}"; shift 2 ;;
            -b | --build ) banner_build_boolean=true; shift ;;
#           -i | --install ) banner_install_boolean=true; shift ;;
            -i | --install ) banner_install; shift ;;
            -j | --java-options ) banner_java_options="${2}"; shift 2 ;;
            -o | --options ) banner_options="${2}"; shift 2 ;;
            -s | --start ) banner_start ${2}; shift 2 ;;
            -u | --update-launcer) banner_launcher_update "${0}"; shift ;;
            -- ) shift; break ;;
            * ) break ;;
        esac
    done
#   if [ ${banner_build_boolean:-false} -a ${banner_install_boolean:-false} ]; then
#   else
#   fi
}
main $*